apiVersion: v1
kind: Service
metadata:
  name: business-platform
  namespace: business-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: business-platform
  ports:
    - name: http
      port: 80
      targetPort: 8000
