"""added business table

Revision ID: 17dd90402a9f
Revises: 0001
Create Date: 2026-08-27 08:41:50.271743
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17dd90402a9f'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_type', sa.Enum('business', 'company', 'nonprofit', 'government', 'cooperative', 'partnership', 'sole_proprietorship', name='business_type'), nullable=False),
    sa.Column('legal_structure', sa.Enum('sole_proprietorship', 'partnership', 'llc', 'c_corporation', 's_corporation', 'nonprofit', 'cooperative', 'government_entity', 'other', name='legal_structure'), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', 'dissolved', name='business_status'), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('tax_identification_number', sa.String(length=100), nullable=True),
    sa.Column('incorporation_date', sa.Date(), nullable=True),
    sa.Column('country_of_incorporation', sa.String(length=100), nullable=True),
    sa.Column('state_of_incorporation', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=True),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('industry_code', sa.String(length=50), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('annual_revenue', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('stock_symbol', sa.String(length=20), nullable=True),
    sa.Column('stock_exchange', sa.String(length=50), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_business_type'), 'businesses', ['business_type'], unique=False)
    op.create_index(op.f('ix_businesses_email'), 'businesses', ['email'], unique=False)
    op.create_index(op.f('ix_businesses_industry'), 'businesses', ['industry'], unique=False)
    op.create_index(op.f('ix_businesses_is_deleted'), 'businesses', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_businesses_is_public'), 'businesses', ['is_public'], unique=False)
    op.create_index(op.f('ix_businesses_name'), 'businesses', ['name'], unique=False)
    op.create_index(op.f('ix_businesses_owner_user_id'), 'businesses', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_businesses_registration_number'), 'businesses', ['registration_number'], unique=False)
    op.create_index(op.f('ix_businesses_status'), 'businesses', ['status'], unique=False)
    op.create_index(op.f('ix_businesses_stock_symbol'), 'businesses', ['stock_symbol'], unique=False)
    op.create_index(op.f('ix_businesses_tax_identification_number'), 'businesses', ['tax_identification_number'], unique=False)
    op.create_table('business_ownerships',
    sa.Column('owner_business_id', sa.UUID(), nullable=False),
    sa.Column('owned_business_id', sa.UUID(), nullable=False),
    sa.Column('ownership_type', sa.Enum('parent', 'subsidiary', 'majority', 'minority', 'joint_venture', 'affiliate', name='ownership_type'), nullable=False),
    sa.Column('ownership_percentage', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owned_business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_ownerships_is_deleted'), 'business_ownerships', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_business_ownerships_owned_business_id'), 'business_ownerships', ['owned_business_id'], unique=False)
    op.create_index(op.f('ix_business_ownerships_owner_business_id'), 'business_ownerships', ['owner_business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_ownerships_owner_business_id'), table_name='business_ownerships')
    op.drop_index(op.f('ix_business_ownerships_owned_business_id'), table_name='business_ownerships')
    op.drop_index(op.f('ix_business_ownerships_is_deleted'), table_name='business_ownerships')
    op.drop_table('business_ownerships')
    op.drop_index(op.f('ix_businesses_tax_identification_number'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_stock_symbol'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_status'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_registration_number'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_owner_user_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_name'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_is_public'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_is_deleted'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_industry'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_email'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_business_type'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
