"""redesigned tables

Revision ID: 872a9ed5e3ef
Revises: 
Create Date: 2026-08-28 18:01:00.008095
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '872a9ed5e3ef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Legal or primary business name'),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_type', sa.String(length=30), nullable=False),
    sa.Column('legal_structure', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('tax_identification_number', sa.String(length=100), nullable=True),
    sa.Column('incorporation_date', sa.Date(), nullable=True),
    sa.Column('country_of_incorporation', sa.String(length=100), nullable=True),
    sa.Column('state_of_incorporation', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=2083), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=True),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('industry_code', sa.String(length=50), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('annual_revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True, comment='ISO 4217 currency code'),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('stock_symbol', sa.String(length=20), nullable=True),
    sa.Column('stock_exchange', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='UUID of the user who created this record'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Flag indicating if the record has been soft-deleted'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted'),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True, comment='UUID of the user who soft-deleted this record'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number for optimistic concurrency control'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_business_type'), 'businesses', ['business_type'], unique=False)
    op.create_index(op.f('ix_businesses_country'), 'businesses', ['country'], unique=False)
    op.create_index(op.f('ix_businesses_created_at'), 'businesses', ['created_at'], unique=False)
    op.create_index(op.f('ix_businesses_created_by_id'), 'businesses', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_businesses_deleted_at'), 'businesses', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_businesses_deleted_by_id'), 'businesses', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_businesses_id'), 'businesses', ['id'], unique=False)
    op.create_index(op.f('ix_businesses_industry'), 'businesses', ['industry'], unique=False)
    op.create_index(op.f('ix_businesses_is_deleted'), 'businesses', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_businesses_name'), 'businesses', ['name'], unique=False)
    op.create_index(op.f('ix_businesses_registration_number'), 'businesses', ['registration_number'], unique=False)
    op.create_index(op.f('ix_businesses_status'), 'businesses', ['status'], unique=False)
    op.create_index(op.f('ix_businesses_tax_identification_number'), 'businesses', ['tax_identification_number'], unique=False)
    op.create_index(op.f('ix_businesses_updated_at'), 'businesses', ['updated_at'], unique=False)
    op.create_index(op.f('ix_businesses_updated_by_id'), 'businesses', ['updated_by_id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False, comment='Unique login handle'),
    sa.Column('email', sa.String(length=320), nullable=False, comment='Primary contact email'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment='Display name shown in the dashboard'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='bcrypt hash — never expose via a schema'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='Coarse role carried inside the JWT'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the account can authenticate'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='UUID of the user who created this record'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Flag indicating if the record has been soft-deleted'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted'),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True, comment='UUID of the user who soft-deleted this record'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number for optimistic concurrency control'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_created_by_id'), 'users', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_deleted_by_id'), 'users', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_index(op.f('ix_users_updated_by_id'), 'users', ['updated_by_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.UUID(), nullable=True, comment='Null for system-initiated actions'),
    sa.Column('business_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False, comment="e.g. 'business.update', 'employee.terminate'"),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='UUID of the user who created this record'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Flag indicating if the record has been soft-deleted'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted'),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True, comment='UUID of the user who soft-deleted this record'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number for optimistic concurrency control'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_business_id'), 'audit_logs', ['business_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_by_id'), 'audit_logs', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_deleted_at'), 'audit_logs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_deleted_by_id'), 'audit_logs', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_is_deleted'), 'audit_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_updated_at'), 'audit_logs', ['updated_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_updated_by_id'), 'audit_logs', ['updated_by_id'], unique=False)
    op.create_table('business_relationships',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('related_business_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ownership_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='UUID of the user who created this record'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Flag indicating if the record has been soft-deleted'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted'),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True, comment='UUID of the user who soft-deleted this record'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number for optimistic concurrency control'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_relationships_business_id'), 'business_relationships', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_relationships_created_at'), 'business_relationships', ['created_at'], unique=False)
    op.create_index(op.f('ix_business_relationships_created_by_id'), 'business_relationships', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_business_relationships_deleted_at'), 'business_relationships', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_business_relationships_deleted_by_id'), 'business_relationships', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_business_relationships_id'), 'business_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_business_relationships_is_deleted'), 'business_relationships', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_business_relationships_related_business_id'), 'business_relationships', ['related_business_id'], unique=False)
    op.create_index(op.f('ix_business_relationships_relationship_type'), 'business_relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_business_relationships_status'), 'business_relationships', ['status'], unique=False)
    op.create_index(op.f('ix_business_relationships_updated_at'), 'business_relationships', ['updated_at'], unique=False)
    op.create_index(op.f('ix_business_relationships_updated_by_id'), 'business_relationships', ['updated_by_id'], unique=False)
    op.create_table('documents',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='UUID of the user who created this record'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Flag indicating if the record has been soft-deleted'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted'),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True, comment='UUID of the user who soft-deleted this record'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number for optimistic concurrency control'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_business_id'), 'documents', ['business_id'], unique=False)
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_created_by_id'), 'documents', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_documents_deleted_at'), 'documents', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_documents_deleted_by_id'), 'documents', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_is_deleted'), 'documents', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_updated_at'), 'documents', ['updated_at'], unique=False)
    op.create_index(op.f('ix_documents_updated_by_id'), 'documents', ['updated_by_id'], unique=False)
    op.create_table('financial_accounts',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('account_name', sa.String(length=150), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('institution_name', sa.String(length=150), nullable=True),
    sa.Column('account_number_masked', sa.String(length=20), nullable=True, comment="Masked display value only, e.g. '****1234'"),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='ISO 4217 currency code'),
    sa.Column('current_balance', sa.Numeric(precision=18, scale=2), nullable=True, comment='Cached balance — recomputed from transactions periodically'),
    sa.Column('opened_date', sa.Date(), nullable=True),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='UUID of the user who created this record'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Flag indicating if the record has been soft-deleted'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted'),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True, comment='UUID of the user who soft-deleted this record'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number for optimistic concurrency control'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_accounts_account_type'), 'financial_accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_financial_accounts_business_id'), 'financial_accounts', ['business_id'], unique=False)
    op.create_index(op.f('ix_financial_accounts_created_at'), 'financial_accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_financial_accounts_created_by_id'), 'financial_accounts', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_financial_accounts_deleted_at'), 'financial_accounts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_financial_accounts_deleted_by_id'), 'financial_accounts', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_financial_accounts_id'), 'financial_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_financial_accounts_is_deleted'), 'financial_accounts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_financial_accounts_status'), 'financial_accounts', ['status'], unique=False)
    op.create_index(op.f('ix_financial_accounts_updated_at'), 'financial_accounts', ['updated_at'], unique=False)
    op.create_index(op.f('ix_financial_accounts_updated_by_id'), 'financial_accounts', ['updated_by_id'], unique=False)
    op.create_table('memberships',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invited_by_id', sa.UUID(), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='UUID of the user who created this record'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Flag indicating if the record has been soft-deleted'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted'),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True, comment='UUID of the user who soft-deleted this record'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number for optimistic concurrency control'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memberships_business_id'), 'memberships', ['business_id'], unique=False)
    op.create_index(op.f('ix_memberships_created_at'), 'memberships', ['created_at'], unique=False)
    op.create_index(op.f('ix_memberships_created_by_id'), 'memberships', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_memberships_deleted_at'), 'memberships', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_memberships_deleted_by_id'), 'memberships', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_memberships_id'), 'memberships', ['id'], unique=False)
    op.create_index(op.f('ix_memberships_is_deleted'), 'memberships', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_memberships_role'), 'memberships', ['role'], unique=False)
    op.create_index(op.f('ix_memberships_status'), 'memberships', ['status'], unique=False)
    op.create_index(op.f('ix_memberships_updated_at'), 'memberships', ['updated_at'], unique=False)
    op.create_index(op.f('ix_memberships_updated_by_id'), 'memberships', ['updated_by_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('people',
    sa.Column('primary_business_id', sa.UUID(), nullable=True, comment='Business scope the person was originally created under'),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=True),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='UUID of the user who created this record'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Flag indicating if the record has been soft-deleted'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted'),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True, comment='UUID of the user who soft-deleted this record'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number for optimistic concurrency control'),
    sa.ForeignKeyConstraint(['primary_business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_created_at'), 'people', ['created_at'], unique=False)
    op.create_index(op.f('ix_people_created_by_id'), 'people', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_people_deleted_at'), 'people', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_people_deleted_by_id'), 'people', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_people_email'), 'people', ['email'], unique=False)
    op.create_index(op.f('ix_people_first_name'), 'people', ['first_name'], unique=False)
    op.create_index(op.f('ix_people_id'), 'people', ['id'], unique=False)
    op.create_index(op.f('ix_people_is_deleted'), 'people', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_people_last_name'), 'people', ['last_name'], unique=False)
    op.create_index(op.f('ix_people_primary_business_id'), 'people', ['primary_business_id'], unique=False)
    op.create_index(op.f('ix_people_updated_at'), 'people', ['updated_at'], unique=False)
    op.create_index(op.f('ix_people_updated_by_id'), 'people', ['updated_by_id'], unique=False)
    op.create_table('tax_profiles',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=100), nullable=False, comment='Country or state the profile is filed under'),
    sa.Column('filing_frequency', sa.String(length=30), nullable=True),
    sa.Column('fiscal_year_end', sa.String(length=5), nullable=True, comment='MM-DD of the fiscal year end'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='UUID of the user who created this record'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Flag indicating if the record has been soft-deleted'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted'),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True, comment='UUID of the user who soft-deleted this record'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number for optimistic concurrency control'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_profiles_business_id'), 'tax_profiles', ['business_id'], unique=False)
    op.create_index(op.f('ix_tax_profiles_created_at'), 'tax_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_tax_profiles_created_by_id'), 'tax_profiles', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_tax_profiles_deleted_at'), 'tax_profiles', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tax_profiles_deleted_by_id'), 'tax_profiles', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_tax_profiles_id'), 'tax_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_tax_profiles_is_deleted'), 'tax_profiles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_tax_profiles_jurisdiction'), 'tax_profiles', ['jurisdiction'], unique=False)
    op.create_index(op.f('ix_tax_profiles_status'), 'tax_profiles', ['status'], unique=False)
    op.create_index(op.f('ix_tax_profiles_updated_at'), 'tax_profiles', ['updated_at'], unique=False)
    op.create_index(op.f('ix_tax_profiles_updated_by_id'), 'tax_profiles', ['updated_by_id'], unique=False)
    op.create_table('compensation_records',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('compensation_type', sa.String(length=20), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='ISO 4217 currency code'),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='UUID of the user who created this record'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Flag indicating if the record has been soft-deleted'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted'),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True, comment='UUID of the user who soft-deleted this record'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number for optimistic concurrency control'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compensation_records_business_id'), 'compensation_records', ['business_id'], unique=False)
    op.create_index(op.f('ix_compensation_records_compensation_type'), 'compensation_records', ['compensation_type'], unique=False)
    op.create_index(op.f('ix_compensation_records_created_at'), 'compensation_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_compensation_records_created_by_id'), 'compensation_records', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_compensation_records_deleted_at'), 'compensation_records', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_compensation_records_deleted_by_id'), 'compensation_records', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_compensation_records_effective_date'), 'compensation_records', ['effective_date'], unique=False)
    op.create_index(op.f('ix_compensation_records_id'), 'compensation_records', ['id'], unique=False)
    op.create_index(op.f('ix_compensation_records_is_current'), 'compensation_records', ['is_current'], unique=False)
    op.create_index(op.f('ix_compensation_records_is_deleted'), 'compensation_records', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_compensation_records_person_id'), 'compensation_records', ['person_id'], unique=False)
    op.create_index(op.f('ix_compensation_records_updated_at'), 'compensation_records', ['updated_at'], unique=False)
    op.create_index(op.f('ix_compensation_records_updated_by_id'), 'compensation_records', ['updated_by_id'], unique=False)
    op.create_table('contacts',
    sa.Column('business_id', sa.UUID(), nullable=True),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('contact_type', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='UUID of the user who created this record'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Flag indicating if the record has been soft-deleted'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted'),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True, comment='UUID of the user who soft-deleted this record'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number for optimistic concurrency control'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_business_id'), 'contacts', ['business_id'], unique=False)
    op.create_index(op.f('ix_contacts_contact_type'), 'contacts', ['contact_type'], unique=False)
    op.create_index(op.f('ix_contacts_created_at'), 'contacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_contacts_created_by_id'), 'contacts', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_contacts_deleted_at'), 'contacts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_contacts_deleted_by_id'), 'contacts', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_index(op.f('ix_contacts_is_deleted'), 'contacts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_contacts_person_id'), 'contacts', ['person_id'], unique=False)
    op.create_index(op.f('ix_contacts_updated_at'), 'contacts', ['updated_at'], unique=False)
    op.create_index(op.f('ix_contacts_updated_by_id'), 'contacts', ['updated_by_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False, comment='Object storage key/path, not a public URL'),
    sa.Column('mime_type', sa.String(length=150), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('change_notes', sa.Text(), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='UUID of the user who created this record'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Flag indicating if the record has been soft-deleted'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted'),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True, comment='UUID of the user who soft-deleted this record'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number for optimistic concurrency control'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_versions_created_at'), 'document_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_versions_created_by_id'), 'document_versions', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_document_versions_deleted_at'), 'document_versions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_document_versions_deleted_by_id'), 'document_versions', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_versions_id'), 'document_versions', ['id'], unique=False)
    op.create_index(op.f('ix_document_versions_is_deleted'), 'document_versions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_document_versions_updated_at'), 'document_versions', ['updated_at'], unique=False)
    op.create_index(op.f('ix_document_versions_updated_by_id'), 'document_versions', ['updated_by_id'], unique=False)
    op.create_table('employees',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True, comment="Self-referential — this employee's manager"),
    sa.Column('employee_number', sa.String(length=50), nullable=True),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('employment_type', sa.String(length=20), nullable=False),
    sa.Column('employment_status', sa.String(length=20), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('termination_reason', sa.Text(), nullable=True),
    sa.Column('work_email', sa.String(length=320), nullable=True),
    sa.Column('work_phone', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='UUID of the user who created this record'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Flag indicating if the record has been soft-deleted'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted'),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True, comment='UUID of the user who soft-deleted this record'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number for optimistic concurrency control'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_business_id'), 'employees', ['business_id'], unique=False)
    op.create_index(op.f('ix_employees_created_at'), 'employees', ['created_at'], unique=False)
    op.create_index(op.f('ix_employees_created_by_id'), 'employees', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_employees_deleted_at'), 'employees', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_employees_deleted_by_id'), 'employees', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    op.create_index(op.f('ix_employees_employee_number'), 'employees', ['employee_number'], unique=False)
    op.create_index(op.f('ix_employees_employment_status'), 'employees', ['employment_status'], unique=False)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_is_deleted'), 'employees', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_employees_manager_id'), 'employees', ['manager_id'], unique=False)
    op.create_index(op.f('ix_employees_person_id'), 'employees', ['person_id'], unique=False)
    op.create_index(op.f('ix_employees_updated_at'), 'employees', ['updated_at'], unique=False)
    op.create_index(op.f('ix_employees_updated_by_id'), 'employees', ['updated_by_id'], unique=False)
    op.create_table('events',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_rule', sa.String(length=255), nullable=True, comment='RFC 5545 RRULE string, if is_recurring'),
    sa.Column('reminder_days_before', sa.Integer(), nullable=True),
    sa.Column('related_document_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='UUID of the user who created this record'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Flag indicating if the record has been soft-deleted'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted'),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True, comment='UUID of the user who soft-deleted this record'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number for optimistic concurrency control'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_business_id'), 'events', ['business_id'], unique=False)
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_created_by_id'), 'events', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_events_deleted_at'), 'events', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_events_deleted_by_id'), 'events', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_events_end_date'), 'events', ['end_date'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_is_deleted'), 'events', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_events_start_date'), 'events', ['start_date'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_index(op.f('ix_events_updated_at'), 'events', ['updated_at'], unique=False)
    op.create_index(op.f('ix_events_updated_by_id'), 'events', ['updated_by_id'], unique=False)
    op.create_table('financial_transactions',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('counterparty_name', sa.String(length=255), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='UUID of the user who created this record'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Flag indicating if the record has been soft-deleted'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted'),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True, comment='UUID of the user who soft-deleted this record'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number for optimistic concurrency control'),
    sa.ForeignKeyConstraint(['account_id'], ['financial_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_transactions_account_id'), 'financial_transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_business_id'), 'financial_transactions', ['business_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_category'), 'financial_transactions', ['category'], unique=False)
    op.create_index(op.f('ix_financial_transactions_created_at'), 'financial_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_financial_transactions_created_by_id'), 'financial_transactions', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_deleted_at'), 'financial_transactions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_financial_transactions_deleted_by_id'), 'financial_transactions', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_id'), 'financial_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_is_deleted'), 'financial_transactions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_financial_transactions_reference_number'), 'financial_transactions', ['reference_number'], unique=False)
    op.create_index(op.f('ix_financial_transactions_status'), 'financial_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_financial_transactions_transaction_date'), 'financial_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_financial_transactions_transaction_type'), 'financial_transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_financial_transactions_updated_at'), 'financial_transactions', ['updated_at'], unique=False)
    op.create_index(op.f('ix_financial_transactions_updated_by_id'), 'financial_transactions', ['updated_by_id'], unique=False)
    op.create_table('leaders',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('appointed_date', sa.Date(), nullable=True),
    sa.Column('resigned_date', sa.Date(), nullable=True),
    sa.Column('is_signatory', sa.Boolean(), nullable=False),
    sa.Column('voting_rights', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='UUID of the user who created this record'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Flag indicating if the record has been soft-deleted'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted'),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True, comment='UUID of the user who soft-deleted this record'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number for optimistic concurrency control'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaders_business_id'), 'leaders', ['business_id'], unique=False)
    op.create_index(op.f('ix_leaders_created_at'), 'leaders', ['created_at'], unique=False)
    op.create_index(op.f('ix_leaders_created_by_id'), 'leaders', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_leaders_deleted_at'), 'leaders', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_leaders_deleted_by_id'), 'leaders', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_leaders_id'), 'leaders', ['id'], unique=False)
    op.create_index(op.f('ix_leaders_is_deleted'), 'leaders', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_leaders_person_id'), 'leaders', ['person_id'], unique=False)
    op.create_index(op.f('ix_leaders_status'), 'leaders', ['status'], unique=False)
    op.create_index(op.f('ix_leaders_title'), 'leaders', ['title'], unique=False)
    op.create_index(op.f('ix_leaders_updated_at'), 'leaders', ['updated_at'], unique=False)
    op.create_index(op.f('ix_leaders_updated_by_id'), 'leaders', ['updated_by_id'], unique=False)
    op.create_table('ownership_records',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('ownership_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('shares_count', sa.Integer(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='UUID of the user who created this record'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Flag indicating if the record has been soft-deleted'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted'),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True, comment='UUID of the user who soft-deleted this record'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number for optimistic concurrency control'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ownership_records_business_id'), 'ownership_records', ['business_id'], unique=False)
    op.create_index(op.f('ix_ownership_records_created_at'), 'ownership_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_ownership_records_created_by_id'), 'ownership_records', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_ownership_records_deleted_at'), 'ownership_records', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_ownership_records_deleted_by_id'), 'ownership_records', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_ownership_records_id'), 'ownership_records', ['id'], unique=False)
    op.create_index(op.f('ix_ownership_records_is_deleted'), 'ownership_records', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ownership_records_person_id'), 'ownership_records', ['person_id'], unique=False)
    op.create_index(op.f('ix_ownership_records_status'), 'ownership_records', ['status'], unique=False)
    op.create_index(op.f('ix_ownership_records_updated_at'), 'ownership_records', ['updated_at'], unique=False)
    op.create_index(op.f('ix_ownership_records_updated_by_id'), 'ownership_records', ['updated_by_id'], unique=False)
    op.create_table('tax_identifiers',
    sa.Column('tax_profile_id', sa.UUID(), nullable=False),
    sa.Column('identifier_type', sa.String(length=10), nullable=False),
    sa.Column('identifier_value_encrypted', sa.Text(), nullable=False, comment='Encrypted at the application layer — never store plaintext'),
    sa.Column('identifier_last4', sa.String(length=4), nullable=True, comment='Last 4 characters — safe for masked display'),
    sa.Column('issued_country', sa.String(length=100), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='UUID of the user who created this record'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Flag indicating if the record has been soft-deleted'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted'),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True, comment='UUID of the user who soft-deleted this record'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number for optimistic concurrency control'),
    sa.ForeignKeyConstraint(['tax_profile_id'], ['tax_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_identifiers_created_at'), 'tax_identifiers', ['created_at'], unique=False)
    op.create_index(op.f('ix_tax_identifiers_created_by_id'), 'tax_identifiers', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_tax_identifiers_deleted_at'), 'tax_identifiers', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tax_identifiers_deleted_by_id'), 'tax_identifiers', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_tax_identifiers_id'), 'tax_identifiers', ['id'], unique=False)
    op.create_index(op.f('ix_tax_identifiers_identifier_type'), 'tax_identifiers', ['identifier_type'], unique=False)
    op.create_index(op.f('ix_tax_identifiers_is_deleted'), 'tax_identifiers', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_tax_identifiers_tax_profile_id'), 'tax_identifiers', ['tax_profile_id'], unique=False)
    op.create_index(op.f('ix_tax_identifiers_updated_at'), 'tax_identifiers', ['updated_at'], unique=False)
    op.create_index(op.f('ix_tax_identifiers_updated_by_id'), 'tax_identifiers', ['updated_by_id'], unique=False)
    op.create_table('employee_history',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('previous_job_title', sa.String(length=150), nullable=True),
    sa.Column('new_job_title', sa.String(length=150), nullable=True),
    sa.Column('previous_department', sa.String(length=150), nullable=True),
    sa.Column('new_department', sa.String(length=150), nullable=True),
    sa.Column('previous_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='UUID of the user who created this record'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Flag indicating if the record has been soft-deleted'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted'),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True, comment='UUID of the user who soft-deleted this record'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number for optimistic concurrency control'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_history_created_at'), 'employee_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_employee_history_created_by_id'), 'employee_history', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_employee_history_deleted_at'), 'employee_history', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_employee_history_deleted_by_id'), 'employee_history', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_employee_history_employee_id'), 'employee_history', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_history_event_type'), 'employee_history', ['event_type'], unique=False)
    op.create_index(op.f('ix_employee_history_id'), 'employee_history', ['id'], unique=False)
    op.create_index(op.f('ix_employee_history_is_deleted'), 'employee_history', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_employee_history_updated_at'), 'employee_history', ['updated_at'], unique=False)
    op.create_index(op.f('ix_employee_history_updated_by_id'), 'employee_history', ['updated_by_id'], unique=False)
    op.create_table('ownership_transitions',
    sa.Column('ownership_record_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('transitioned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transitioned_by_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='UUID of the user who created this record'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Flag indicating if the record has been soft-deleted'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted'),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True, comment='UUID of the user who soft-deleted this record'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number for optimistic concurrency control'),
    sa.ForeignKeyConstraint(['ownership_record_id'], ['ownership_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transitioned_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ownership_transitions_created_at'), 'ownership_transitions', ['created_at'], unique=False)
    op.create_index(op.f('ix_ownership_transitions_created_by_id'), 'ownership_transitions', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_ownership_transitions_deleted_at'), 'ownership_transitions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_ownership_transitions_deleted_by_id'), 'ownership_transitions', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_ownership_transitions_id'), 'ownership_transitions', ['id'], unique=False)
    op.create_index(op.f('ix_ownership_transitions_is_deleted'), 'ownership_transitions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ownership_transitions_ownership_record_id'), 'ownership_transitions', ['ownership_record_id'], unique=False)
    op.create_index(op.f('ix_ownership_transitions_updated_at'), 'ownership_transitions', ['updated_at'], unique=False)
    op.create_index(op.f('ix_ownership_transitions_updated_by_id'), 'ownership_transitions', ['updated_by_id'], unique=False)
    op.create_table('tasks',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('related_event_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='UUID of the user who created this record'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Flag indicating if the record has been soft-deleted'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted'),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True, comment='UUID of the user who soft-deleted this record'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number for optimistic concurrency control'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assigned_to_id'), 'tasks', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_tasks_business_id'), 'tasks', ['business_id'], unique=False)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_created_by_id'), 'tasks', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_tasks_deleted_at'), 'tasks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tasks_deleted_by_id'), 'tasks', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_is_deleted'), 'tasks', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_start_date'), 'tasks', ['start_date'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_updated_at'), 'tasks', ['updated_at'], unique=False)
    op.create_index(op.f('ix_tasks_updated_by_id'), 'tasks', ['updated_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_updated_by_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_updated_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_start_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_is_deleted'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_deleted_by_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_deleted_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_by_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_business_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_ownership_transitions_updated_by_id'), table_name='ownership_transitions')
    op.drop_index(op.f('ix_ownership_transitions_updated_at'), table_name='ownership_transitions')
    op.drop_index(op.f('ix_ownership_transitions_ownership_record_id'), table_name='ownership_transitions')
    op.drop_index(op.f('ix_ownership_transitions_is_deleted'), table_name='ownership_transitions')
    op.drop_index(op.f('ix_ownership_transitions_id'), table_name='ownership_transitions')
    op.drop_index(op.f('ix_ownership_transitions_deleted_by_id'), table_name='ownership_transitions')
    op.drop_index(op.f('ix_ownership_transitions_deleted_at'), table_name='ownership_transitions')
    op.drop_index(op.f('ix_ownership_transitions_created_by_id'), table_name='ownership_transitions')
    op.drop_index(op.f('ix_ownership_transitions_created_at'), table_name='ownership_transitions')
    op.drop_table('ownership_transitions')
    op.drop_index(op.f('ix_employee_history_updated_by_id'), table_name='employee_history')
    op.drop_index(op.f('ix_employee_history_updated_at'), table_name='employee_history')
    op.drop_index(op.f('ix_employee_history_is_deleted'), table_name='employee_history')
    op.drop_index(op.f('ix_employee_history_id'), table_name='employee_history')
    op.drop_index(op.f('ix_employee_history_event_type'), table_name='employee_history')
    op.drop_index(op.f('ix_employee_history_employee_id'), table_name='employee_history')
    op.drop_index(op.f('ix_employee_history_deleted_by_id'), table_name='employee_history')
    op.drop_index(op.f('ix_employee_history_deleted_at'), table_name='employee_history')
    op.drop_index(op.f('ix_employee_history_created_by_id'), table_name='employee_history')
    op.drop_index(op.f('ix_employee_history_created_at'), table_name='employee_history')
    op.drop_table('employee_history')
    op.drop_index(op.f('ix_tax_identifiers_updated_by_id'), table_name='tax_identifiers')
    op.drop_index(op.f('ix_tax_identifiers_updated_at'), table_name='tax_identifiers')
    op.drop_index(op.f('ix_tax_identifiers_tax_profile_id'), table_name='tax_identifiers')
    op.drop_index(op.f('ix_tax_identifiers_is_deleted'), table_name='tax_identifiers')
    op.drop_index(op.f('ix_tax_identifiers_identifier_type'), table_name='tax_identifiers')
    op.drop_index(op.f('ix_tax_identifiers_id'), table_name='tax_identifiers')
    op.drop_index(op.f('ix_tax_identifiers_deleted_by_id'), table_name='tax_identifiers')
    op.drop_index(op.f('ix_tax_identifiers_deleted_at'), table_name='tax_identifiers')
    op.drop_index(op.f('ix_tax_identifiers_created_by_id'), table_name='tax_identifiers')
    op.drop_index(op.f('ix_tax_identifiers_created_at'), table_name='tax_identifiers')
    op.drop_table('tax_identifiers')
    op.drop_index(op.f('ix_ownership_records_updated_by_id'), table_name='ownership_records')
    op.drop_index(op.f('ix_ownership_records_updated_at'), table_name='ownership_records')
    op.drop_index(op.f('ix_ownership_records_status'), table_name='ownership_records')
    op.drop_index(op.f('ix_ownership_records_person_id'), table_name='ownership_records')
    op.drop_index(op.f('ix_ownership_records_is_deleted'), table_name='ownership_records')
    op.drop_index(op.f('ix_ownership_records_id'), table_name='ownership_records')
    op.drop_index(op.f('ix_ownership_records_deleted_by_id'), table_name='ownership_records')
    op.drop_index(op.f('ix_ownership_records_deleted_at'), table_name='ownership_records')
    op.drop_index(op.f('ix_ownership_records_created_by_id'), table_name='ownership_records')
    op.drop_index(op.f('ix_ownership_records_created_at'), table_name='ownership_records')
    op.drop_index(op.f('ix_ownership_records_business_id'), table_name='ownership_records')
    op.drop_table('ownership_records')
    op.drop_index(op.f('ix_leaders_updated_by_id'), table_name='leaders')
    op.drop_index(op.f('ix_leaders_updated_at'), table_name='leaders')
    op.drop_index(op.f('ix_leaders_title'), table_name='leaders')
    op.drop_index(op.f('ix_leaders_status'), table_name='leaders')
    op.drop_index(op.f('ix_leaders_person_id'), table_name='leaders')
    op.drop_index(op.f('ix_leaders_is_deleted'), table_name='leaders')
    op.drop_index(op.f('ix_leaders_id'), table_name='leaders')
    op.drop_index(op.f('ix_leaders_deleted_by_id'), table_name='leaders')
    op.drop_index(op.f('ix_leaders_deleted_at'), table_name='leaders')
    op.drop_index(op.f('ix_leaders_created_by_id'), table_name='leaders')
    op.drop_index(op.f('ix_leaders_created_at'), table_name='leaders')
    op.drop_index(op.f('ix_leaders_business_id'), table_name='leaders')
    op.drop_table('leaders')
    op.drop_index(op.f('ix_financial_transactions_updated_by_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_updated_at'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_transaction_type'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_transaction_date'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_status'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_reference_number'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_is_deleted'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_deleted_by_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_deleted_at'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_created_by_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_created_at'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_category'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_business_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_account_id'), table_name='financial_transactions')
    op.drop_table('financial_transactions')
    op.drop_index(op.f('ix_events_updated_by_id'), table_name='events')
    op.drop_index(op.f('ix_events_updated_at'), table_name='events')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_start_date'), table_name='events')
    op.drop_index(op.f('ix_events_is_deleted'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_end_date'), table_name='events')
    op.drop_index(op.f('ix_events_deleted_by_id'), table_name='events')
    op.drop_index(op.f('ix_events_deleted_at'), table_name='events')
    op.drop_index(op.f('ix_events_created_by_id'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_index(op.f('ix_events_business_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_employees_updated_by_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_updated_at'), table_name='employees')
    op.drop_index(op.f('ix_employees_person_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_manager_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_is_deleted'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employment_status'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_department'), table_name='employees')
    op.drop_index(op.f('ix_employees_deleted_by_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_deleted_at'), table_name='employees')
    op.drop_index(op.f('ix_employees_created_by_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_created_at'), table_name='employees')
    op.drop_index(op.f('ix_employees_business_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_document_versions_updated_by_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_updated_at'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_is_deleted'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_deleted_by_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_deleted_at'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_created_by_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_created_at'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_contacts_updated_by_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_updated_at'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_person_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_is_deleted'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_deleted_by_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_deleted_at'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_created_by_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_created_at'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_contact_type'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_business_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_compensation_records_updated_by_id'), table_name='compensation_records')
    op.drop_index(op.f('ix_compensation_records_updated_at'), table_name='compensation_records')
    op.drop_index(op.f('ix_compensation_records_person_id'), table_name='compensation_records')
    op.drop_index(op.f('ix_compensation_records_is_deleted'), table_name='compensation_records')
    op.drop_index(op.f('ix_compensation_records_is_current'), table_name='compensation_records')
    op.drop_index(op.f('ix_compensation_records_id'), table_name='compensation_records')
    op.drop_index(op.f('ix_compensation_records_effective_date'), table_name='compensation_records')
    op.drop_index(op.f('ix_compensation_records_deleted_by_id'), table_name='compensation_records')
    op.drop_index(op.f('ix_compensation_records_deleted_at'), table_name='compensation_records')
    op.drop_index(op.f('ix_compensation_records_created_by_id'), table_name='compensation_records')
    op.drop_index(op.f('ix_compensation_records_created_at'), table_name='compensation_records')
    op.drop_index(op.f('ix_compensation_records_compensation_type'), table_name='compensation_records')
    op.drop_index(op.f('ix_compensation_records_business_id'), table_name='compensation_records')
    op.drop_table('compensation_records')
    op.drop_index(op.f('ix_tax_profiles_updated_by_id'), table_name='tax_profiles')
    op.drop_index(op.f('ix_tax_profiles_updated_at'), table_name='tax_profiles')
    op.drop_index(op.f('ix_tax_profiles_status'), table_name='tax_profiles')
    op.drop_index(op.f('ix_tax_profiles_jurisdiction'), table_name='tax_profiles')
    op.drop_index(op.f('ix_tax_profiles_is_deleted'), table_name='tax_profiles')
    op.drop_index(op.f('ix_tax_profiles_id'), table_name='tax_profiles')
    op.drop_index(op.f('ix_tax_profiles_deleted_by_id'), table_name='tax_profiles')
    op.drop_index(op.f('ix_tax_profiles_deleted_at'), table_name='tax_profiles')
    op.drop_index(op.f('ix_tax_profiles_created_by_id'), table_name='tax_profiles')
    op.drop_index(op.f('ix_tax_profiles_created_at'), table_name='tax_profiles')
    op.drop_index(op.f('ix_tax_profiles_business_id'), table_name='tax_profiles')
    op.drop_table('tax_profiles')
    op.drop_index(op.f('ix_people_updated_by_id'), table_name='people')
    op.drop_index(op.f('ix_people_updated_at'), table_name='people')
    op.drop_index(op.f('ix_people_primary_business_id'), table_name='people')
    op.drop_index(op.f('ix_people_last_name'), table_name='people')
    op.drop_index(op.f('ix_people_is_deleted'), table_name='people')
    op.drop_index(op.f('ix_people_id'), table_name='people')
    op.drop_index(op.f('ix_people_first_name'), table_name='people')
    op.drop_index(op.f('ix_people_email'), table_name='people')
    op.drop_index(op.f('ix_people_deleted_by_id'), table_name='people')
    op.drop_index(op.f('ix_people_deleted_at'), table_name='people')
    op.drop_index(op.f('ix_people_created_by_id'), table_name='people')
    op.drop_index(op.f('ix_people_created_at'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_updated_by_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_updated_at'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_status'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_role'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_is_deleted'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_deleted_by_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_deleted_at'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_created_by_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_created_at'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_business_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_financial_accounts_updated_by_id'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_updated_at'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_status'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_is_deleted'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_id'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_deleted_by_id'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_deleted_at'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_created_by_id'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_created_at'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_business_id'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_account_type'), table_name='financial_accounts')
    op.drop_table('financial_accounts')
    op.drop_index(op.f('ix_documents_updated_by_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_updated_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_deleted'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_deleted_by_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_deleted_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_by_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_business_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_business_relationships_updated_by_id'), table_name='business_relationships')
    op.drop_index(op.f('ix_business_relationships_updated_at'), table_name='business_relationships')
    op.drop_index(op.f('ix_business_relationships_status'), table_name='business_relationships')
    op.drop_index(op.f('ix_business_relationships_relationship_type'), table_name='business_relationships')
    op.drop_index(op.f('ix_business_relationships_related_business_id'), table_name='business_relationships')
    op.drop_index(op.f('ix_business_relationships_is_deleted'), table_name='business_relationships')
    op.drop_index(op.f('ix_business_relationships_id'), table_name='business_relationships')
    op.drop_index(op.f('ix_business_relationships_deleted_by_id'), table_name='business_relationships')
    op.drop_index(op.f('ix_business_relationships_deleted_at'), table_name='business_relationships')
    op.drop_index(op.f('ix_business_relationships_created_by_id'), table_name='business_relationships')
    op.drop_index(op.f('ix_business_relationships_created_at'), table_name='business_relationships')
    op.drop_index(op.f('ix_business_relationships_business_id'), table_name='business_relationships')
    op.drop_table('business_relationships')
    op.drop_index(op.f('ix_audit_logs_updated_by_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_updated_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_is_deleted'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_deleted_by_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_deleted_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_by_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_business_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_updated_by_id'), table_name='users')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_by_id'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_by_id'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_businesses_updated_by_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_updated_at'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_tax_identification_number'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_status'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_registration_number'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_name'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_is_deleted'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_industry'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_deleted_by_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_deleted_at'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_created_by_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_created_at'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_country'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_business_type'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
